#!/bin/bash

max_file_count=10
backup_dir="/home/minecraft/backup"
server_dir="/home/minecraft/server"

# Disable autosave to prevent saving during backup
if screen -ls | grep -qF "minecraft-server"; then
    screen -S minecraft-server -X stuff "say Backing up server...^M"
    screen -S minecraft-server -X stuff "save-off^M"
    screen -S minecraft-server -X stuff "save-all^M"
    sleep 5
fi

# Count existing backups
file_count=$(ls "$backup_dir" | wc -l)

# Remove oldest backup if exceeding limit
if (( file_count > max_file_count )); then
    rm "$backup_dir/world-$max_file_count.tgz"
    (( file_count-- ))
fi

# Rename backups to maintain order
for (( i = file_count; i > 0; i-- )); do
    if (( i > 1 )); then
        mv "$backup_dir/world-$((i-1)).tgz" "$backup_dir/world-$i.tgz"
    else
        mv "$backup_dir/world.tgz" "$backup_dir/world-1.tgz"
    fi
done

# Create a new backup
tar -czf "$backup_dir/world.tgz" -C "$server_dir" "world" "world_nether" "world_the_end"

# Re-enable autosave
if screen -ls | grep -qF "minecraft-server"; then
    screen -S minecraft-server -X stuff "say Backup complete!^M"
    screen -S minecraft-server -X stuff "save-on^M"
fi
