#!/bin/bash

# Stop the server
screen -S minecraft-server -X stuff "stop^M"

# Wait for the server to exit cleanly
declare -i timeout=30
while screen -ls | grep -qF "minecraft-server"; do
    printf "Stopping server... "
    sleep 1
    ((timeout--))
    if ((timeout == 0)); then
        echo "Error: Server did not stop within 30 seconds."
        exit 1
    fi
    echo "done!"
done
