#!/bin/sh

paper_api=https://api.papermc.io/v2/projects/paper

# Check arguments
if [ $# -eq 1 ]; then
    version=$1;
elif [ $# -eq 0 ]; then
    # If no version specified, pull the latest
    version=$(curl -s $paper_api | jq -r .versions[-1])
fi

# Check version
if ! curl -s $paper_api | jq -r .versions | grep -q $version; then
    echo "Invalid Paper version: $version"
    exit 1
fi

# Get latest stable build for specified version
build=$(curl -s $paper_api/versions/$version/builds | jq -r '.builds | map(select(.channel == "default") | .build) | .[-1]')

if [ "$build" != "null" ]; then
    # Download JAR file
    jar=$(curl -s $paper_api/versions/$version/builds/$build | jq -r .downloads.application.name)
    curl -o paper.jar $paper_api/versions/$version/builds/$build/downloads/$jar
else
    echo "No stable build for version $version found. Please specify an earlier version."
    exit 1
fi
